import Link from "next/link";
import { requireOrganization } from "@/lib/session";
import { getOrganizationCertificates } from "@/lib/certificates";
import { formatCertificateDate } from "@/lib/certificate-display";
import { PageHeading } from "@/components/ui";
import { RegistrationStatus } from "@/components/registration-status";
export default async function Certificates() {
  const organization = await requireOrganization();
  const certificates = await getOrganizationCertificates(organization.id);
  return <><div className="flex flex-wrap items-start justify-between gap-4"><PageHeading eyebrow="Credential records" title="Issued Certificates" description="Browse certificates saved by your organization and open their details." /><Link className="btn-primary" href="/issue-certificate">Issue Certificate</Link></div><section className="panel overflow-hidden"><div className="border-b border-slate-200 px-6 py-5"><h2 className="font-semibold">All certificates <span className="ml-2 text-sm font-normal text-slate-400">{certificates.length} records</span></h2></div>{certificates.length ? <div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><caption className="sr-only">Your organization&apos;s issued certificates</caption><thead className="bg-slate-50 text-xs text-slate-500"><tr>{["Certificate ID", "Recipient", "Certificate Title", "Issue Date", "Expiration Date", "Status", "View"].map(label => <th scope="col" className="px-6 py-4 font-medium" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{certificates.map(c => <tr key={c.id} className="hover:bg-slate-50"><td className="px-6 py-5 font-mono text-xs">{c.certificateId}</td><td className="px-6 py-5 font-medium">{c.recipientName}</td><td className="px-6 py-5 text-slate-600">{c.certificateTitle}</td><td className="whitespace-nowrap px-6 py-5 text-slate-500">{formatCertificateDate(c.issueDate)}</td><td className="whitespace-nowrap px-6 py-5 text-slate-500">{formatCertificateDate(c.expirationDate)}</td><td className="px-6 py-5"><RegistrationStatus registration={c.blockchainStatus} status={c.status} revocation={c.revocationStatus} /></td><td className="px-6 py-5"><Link href={`/certificates/${c.id}`} aria-label={`View certificate ${c.certificateId}`} className="font-medium text-teal-700 hover:underline">View ↗</Link></td></tr>)}</tbody></table></div> : <div className="px-6 py-14 text-center"><h3 className="text-lg font-semibold">No certificates yet</h3><p className="mt-2 text-sm text-slate-500">Issue your first certificate to see it here.</p><Link className="btn-primary mt-5" href="/issue-certificate">Issue Certificate</Link></div>}</section><p className="mt-4 text-xs text-slate-500">Records are private to your organization. Expiration is checked whenever this page loads.</p></>;
}
