import Link from "next/link";
import { requireOrganization } from "@/lib/session";
import { getOrganizationDashboard } from "@/lib/certificates";
import { formatCertificateDate } from "@/lib/certificate-display";
import { PageHeading } from "@/components/ui";
import { RegistrationStatus } from "@/components/registration-status";
export default async function Dashboard() {
  const organization = await requireOrganization();
  const { counts, total, recent } = await getOrganizationDashboard(organization.id);
  const cards = [["Total Certificates", total], ["Valid Certificates", counts.VALID], ["Expired Certificates", counts.EXPIRED], ["Revoked Certificates", counts.REVOKED]];
  return <><PageHeading eyebrow="Overview" title="Dashboard" description="Welcome back. Status counts include confirmed registrations; total includes pending, failed, and legacy records." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([title, count], index) => <section className="panel p-6" key={title}><h2 className="text-sm font-medium text-slate-500">{title}</h2><p className={`mt-4 text-4xl font-semibold ${["text-slate-900", "text-teal-700", "text-amber-700", "text-rose-700"][index]}`}>{count}</p><p className="mt-3 text-xs text-slate-400">Organization records</p></section>)}</div><section className="mt-8 flex flex-wrap items-center justify-between gap-5 rounded-2xl bg-slate-900 p-7 text-white"><div><h2 className="text-xl font-semibold">Manage your credentials</h2><p className="mt-2 text-sm text-slate-300">Issue a certificate or browse your existing records.</p></div><div className="flex flex-wrap gap-3"><Link className="btn-primary" href="/issue-certificate">Issue Certificate</Link><Link className="rounded-xl border border-slate-600 px-5 py-3 text-sm font-medium hover:bg-slate-800" href="/certificates">View Certificates</Link></div></section><section className="panel mt-8 p-6"><h2 className="text-lg font-semibold">Recent certificates</h2>{recent.length ? <div className="mt-4 divide-y divide-slate-100">{recent.map(c => <div key={c.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><Link href={`/certificates/${c.id}`} className="font-medium hover:text-teal-700">{c.recipientName}</Link><p className="mt-1 text-sm text-slate-500">{c.certificateTitle} · {formatCertificateDate(c.issueDate)}</p></div><RegistrationStatus registration={c.blockchainStatus} status={c.status} revocation={c.revocationStatus} /></div>)}</div> : <p className="py-8 text-sm text-slate-500">No certificates issued yet. Create your first certificate to get started.</p>}</section></>;
}
